site_name: lazy-imports-lite
site_url: https://15r10nk.github.io/lazy-imports-lite/
repo_url: https://github.com/15r10nk/lazy-imports-lite
theme:
  name: material
nav:
- Home: index.md
- Contributing: contributing.md
